### ISSUE TITLE
Ability to toggle webaudio console printing to prevent console spam

### ISSUE THREAD

**Issue by Mista-Tea** [Vurv78/WebAudio#36]
**Is your feature request related to a problem? Please describe.**
Webaudio prints to console when players create a webaudio object. This is a handy feature for determining who is playing what sounds. Unfortunately, given enough players with enough E2s, other console output (like text chat) will quickly become unreadable as this information is printed.

**Describe the solution you'd like**
It would be useful to create a `ClientConVar` or `concommand` to control whether this information is printed to console, and should default to **disabled.**

The information being printed to console feels similar to how `wire_holograms_display_owners` (the concommand) is useful for seeing where and whose holograms are around, but is disabled by default.

From an administrative position, I entirely agree with logging this sort of information so that malicious users can be identified. But for the regular user, this is just going to spam console with information they don't care about. Being able to toggle printing on or off at least gives them the ability to toggle it on whenever they need it, and off otherwise.

**Comment by Vurv78** [comment]
Can definitely do this but I don't know about disabled by default

This repo is pretty much security first, and if an unwitting person joins a server w/o knowing about this convar and especially after #35 letting the server play anything on a client (as long as they don't have their own whitelist) we'd pretty much be no better than streamcore.

There shouldn't be too many popping up though, only if they create a bunch of sounds over a large span of time (Which I'd already consider malicious), and Starfall has no problem with these types of warnings as well.. 

Maybe the problem is also that they might blend in with chat messages since they're colored?

**Comment by Mista-Tea** [comment]
I understand security first.

But playing devil's advocate for a moment, if such a convar/concommand were enabled by default, I envision most scenarios where everyone's console is going to be inundated with sounds, and people are either going to complain about WebAudio, or there will constantly be new players asking how to turn it off. I don't believe either case, enabled or disabled by default, would please everyone.

I've got a console screenshot example someone gave me. Bear in mind, this is all just a single player playing sounds in a server commonly with 20/20 players, a majority of which commonly played sounds via streamcore that have now refactored to webaudio.

![image](https://user-images.githubusercontent.com/5177393/128290900-ca7441aa-57da-49ce-9f60-89569a40cf49.png)

**Comment by Vurv78** [comment]
I see, will do tomorrow. Can also balance it out with a wa_list concommand anyway

**Comment by Vurv78** [comment]
Done, added a wa_verbosity convar that defaults to only show warnings/errors

**Comment by Vurv78** [comment]
Pushed to workshop
